_target_: src.models.defile_module.DefileLitModule
_convert_: object

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.025287943438475857
  weight_decay: 0.025947578859460165

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 2

net:
  _target_: src.models.components.convnet.ConvNetplus
  nb_input_features: 9
  nb_hidden_features_hourly: 64
  nb_layer_hourly: 4
  nb_hidden_features_daily: 32
  nb_layer_daily: 4
  dropout: False

criterion:
  - _target_: src.models.criterion.RMSE
    alpha: 1
    weights: False
  - _target_: src.models.criterion.L2
    alpha: .1

# compile model for faster training with pytorch 2.0
compile: false
