_target_: src.models.defile_module.DefileLitModule
_convert_: object

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.025287943438475857
  weight_decay: 0.025947578859460165

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 2

net:
  _target_: src.models.components.transformer.Transformer
  nb_input_features: 9
  embed_size_hourly: 64
  num_heads_hourly: 8
  num_blocks_hourly: 4
  embed_size_daily: 32
  num_heads_daily: 4
  num_blocks_daily: 2
  drop_prob: 0.1

criterion:
  - _target_: src.models.criterion.RMSE
    alpha: 1
    weights: False
  - _target_: src.models.criterion.L2
    alpha: .1

# compile model for faster training with pytorch 2.0
compile: false
