_target_: src.models.defile_module.DefileLitModule
_convert_: object

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.005881046823535977
  weight_decay: 0.03868890090567428

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

net:
  _target_: src.models.components.unet.UNetplus
  nb_input_features_hourly: ${eval:'4+${len:${data.era5_main_variables}}+${len:${data.era5_hourly_locations}}*${len:${data.era5_hourly_variables}}'}
  nb_layer_hourly: 2
  nb_hidden_features_hourly: 16
  nb_input_features_daily: ${eval:'2+${len:${data.era5_daily_locations}}*${len:${data.era5_daily_variables}}'}
  nb_lag_day :  ${data.lag_day}
  nb_layer_daily: 6
  nb_hidden_features_daily: 128
  nb_output_features: 1
  dropout: True

criterion:
  # - _target_: src.models.criterion.Gaussian
  #   alpha: 1
  # - _target_: src.models.criterion.RMSE
  #  alpha: 1
  # - _target_: src.models.criterion.L2
  #  alpha: 0.01
  #- _target_: src.models.criterion.Poisson
  #  alpha: 1
  - _target_: src.models.criterion.TweedieLoss
    alpha: 1
    p: 1.5

# compile model for faster training with pytorch 2.0
compile: false
