# @package _global_

defaults:
  - _self_
  - data: defile
  - model: default
  - logger: null
  - trainer: default
  - export: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.log_dir}/train/runs/2024-07-11_11-16-10/checkpoints/epoch_009.ckpt
