# @package _global_

defaults:
  - _self_
  - data: defile
  - model: unet
  - logger: csv
  - trainer: default
  - export: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null

task_name: "eval"

tags: ["unet"]

# passing checkpoint path is necessary for evaluation
ckpt_path: null
