# @package _global_

defaults:
  - _self_
  - data: defile
  - model: unet
  - trainer: cpu
  - paths: production
  - hydra: production
  - experiment: null

task_name: "predict"

# passing checkpoint path is necessary for evaluation
ckpt_path_pred: prod/models/${underscore:'${data.species}'}/checkpoints/best.ckpt
