# @package _global_

defaults:
  - _self_
  - data: defile
  - model: unet
  - logger: csv
  - trainer: default
  - export: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "predict"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: prod/models/${data.species}/checkpoints/last.cpkt

train_params: prod/models/${data.species}/csv/version_0/hparams.yaml
