# @package _global_

defaults:
  - _self_
  - data: defile
  - model: unet
  - logger: csv
  - trainer: default
  - export: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "predict"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.log_dir}/train/multiruns/2024-09-11_14-58-53/14/checkpoints/epoch_032.ckpt
