# @package _global_

defaults:
  - _self_
  - data: defile
  - model: unet
  - experiment: production
  - trainer: default
  - paths: default
  - extras: default
  - override /hydra: default  

task_name: "predict"

# passing checkpoint path is necessary for evaluation
ckpt_path_pred: prod/models/${data.species}/checkpoints/best.ckpt

hydra:
  run:
    dir: prod/forecasts/${data.species}/${now:%Y-%m-%d}

