# @package _global_

defaults:
  - _self_
  - data: defile
  - model: default
  - logger: null
  - trainer: default
  - export: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "predict"

# tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.log_dir}/train/runs/2024-09-13_22-49-55/checkpoints/epoch_031.ckpt
