# @package _global_

defaults:
  - _self_
  - data: defile
  - model: unet
  - trainer: cpu
  - paths: production
  - hydra: production  

task_name: "predict"

# passing checkpoint path is necessary for evaluation
ckpt_path_pred: prod/models/${data.species}/checkpoints/best.ckpt

