name: Predict & Deploy Forecasts

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # daily at 3 AM

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-deployment"
  cancel-in-progress: false

jobs:
  predict:
    runs-on: ubuntu-latest
    outputs:
      forecasts-path: ${{ steps.set-path.outputs.path }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache conda environment
        uses: actions/cache@v3
        with:
          path: ~/.conda/envs/defile-env
          key: ${{ runner.os }}-conda-defile-env-${{ hashFiles('environment.yaml') }}
          restore-keys: |
            ${{ runner.os }}-conda-defile-env-

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2

      - name: Create conda environment
        run: |
          conda init bash
          source ~/.bashrc
          conda env create --file=environment.yaml || conda env update --file=environment.yaml

      - name: Run prediction script
        run: |
          conda activate defile-env
          python src/predict.py --multirun experiment=common_buzzard,red_kite,black_kite,honey_buzzard,marsh_harrier,sparrowhawk,kestrel,osprey,hen_harrier,merlin,hobby

      - name: Set forecasts path
        id: set-path
        run: echo "path=prod/forecasts" >> $GITHUB_OUTPUT

      - name: Upload forecasts artifact
        uses: actions/upload-artifact@v3
        with:
          name: forecasts
          path: prod/forecasts/

  deploy_pages:
    runs-on: ubuntu-latest
    needs: predict
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Download forecasts artifact
        uses: actions/download-artifact@v3
        with:
          name: forecasts
          path: www/img

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./www/"

      - name: Deploy Pages
        id: deploy
        uses: actions/deploy-pages@v4

  upload_gce:
    runs-on: ubuntu-latest
    needs: predict
    steps:
      - name: Download forecasts artifact
        uses: actions/download-artifact@v3
        with:
          name: forecasts
          path: prod/forecasts

      - name: Upload forecasts to GCE
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          port: 22
          source: "prod/forecasts/*"
          target: "/home/github-actions/forecasts"
