name: Run predictions and deploy results

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # daily at 3 AM

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-deployment"
  cancel-in-progress: false

jobs:
  # Job 1: Run prediction script
  predict:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2

      - name: Create conda environment
        run: |
          conda init bash
          source ~/.bashrc
          conda env create --file=environment.yaml

      - name: Run prediction script
        run: |
          conda activate defile-env
          python src/predict.py --multirun experiment=common_buzzard,red_kite,black_kite,honey_buzzard,marsh_harrier,sparrowhawk,kestrel,osprey,hen_harrier,merlin,hobby

      - name: Copy forecast outputs for Pages
        run: cp -r prod/forecasts www/img

  # Job 2: Deploy to GitHub Pages
  deploy_pages:
    runs-on: ubuntu-latest
    needs: predict
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./www/"

      - name: Deploy Pages
        id: deploy
        uses: actions/deploy-pages@v4

      - name: List deployed files
        run: ls -R ./www

  # Job 3: Copy forecast outputs to GCE server
  upload_gce:
    runs-on: ubuntu-latest
    needs: predict
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload forecasts to GCE
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          port: 22
          source: "prod/forecasts/*"
          target: "/home/github-actions/forecasts"
