name: Test GCS Artifact Upload/Download

on:
  workflow_dispatch:

jobs:
  upload-to-gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test file
        run: echo "Hello from GitHub Actions!" > test.txt

      - name: Upload artifact to GCE via scp
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.GCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          password: ${{ secrets.GCE_SSH_KEY }}
          port: 22
          source: "test.txt"
          target: "/home/github-actions/"
